trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: SSH@0
    displayName: "Gå til projektmappe"
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
        echo "Gå til projektmappe"
        cd /var/www/frontend/TaskManager-UI || (echo "Mappe ikke fundet" && exit 1)
        pwd
  - task: SSH@0
    displayName: "Hent kode"
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
        echo "Tjekker path"
        pwd
        
        echo "Henter kode"
        git fetch
        git pull

  - task: SSH@0
    displayName: "Opbyg og kør Docker"
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
        echo "Stopper tidligere container"
        docker-compose down
        echo "Opbygger og kører Docker"
        docker-compose up --build -d 
