trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: SSH@0
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
        echo "Going to frontend folder"
        cd /var/www/frontend || mkdir -p /var/www/frontend && cd /var/www/frontend
        
        echo "Cloning git repository"
        git clone https://github.com/MaldeFrank/TaskManager-UI.git
        
        echo "Creating docker image"
        docker stop frontendContainer || echo "No container named frontendContainer"
        docker rm frontendContainer || echo "No container named frontendContainer"
        docker rmi frontendImage || echo "No image named frontendImage"
        docker build -t frontendImage .
        docker run -d --name frontendContainer -p 80:80 frontendImage