
pool:
  vmImage: ubuntu-latest

steps:
  - task: SSH@0
    displayName: "Gå til projektmappe"
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
        echo "Go to project folder"
        cd /var/www/frontend/TaskManager-UI || (echo "Mappe ikke fundet" && exit 1)
        /bin/pwd

  - task: SSH@0
    displayName: "Hent kode"
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
        echo "Tjekker path"
        cd /var/www/frontend/TaskManager-UI || (echo "Kunne ikke skifte til mappe" && exit 1)
        /bin/pwd
        echo "Henter kode"
        echo "Running git fetch:"
        git fetch 2>&1 || echo "Fetch failed"
        echo "Running git pull:"
        git pull 2>&1 || echo "Pull failed"

  - task: SSH@0
    displayName: "Opbyg og kør Docker"
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
        echo "Stopping earlier container"
        cd /var/www/frontend/TaskManager-UI || (echo "Kunne ikke skifte til mappe" && exit 1)
        docker-compose build --no-cache 2>&1
        echo "Running docker-compose up"
        docker-compose up 2>&1